# Database configuration
database:
  path: private/test.db
  schema_path: schema.sql

# LLM configuration
llm:
  generative_model: o3-mini
  embedding_model: text-embedding-ada-002

# Role configuration
roles:
  path: ./roles
  schema_file: Prompt-Schema.md  
  Observers:
    - name: Psychologist
      file: Role-Psychologist.md
    - name: Demographer
      file: Role-Demographer.md
    - name: BehavioralEconomist
      file: Role-BehavioralEconomist.md
    - name: PoliticalScientist
      file: Role-PoliticalScientist.md
  Helpers:
    - name: FactExtractor
      file: Role-FactExtractor.md
    - name: ConsensusMaker
      file: Role-ConsensusMaker.md
    - name: CoverageAssessor
      file: Role-CoverageAssessor.md
    - name: KeywordExtractor
      file: Role-KeywordExtractor.md
    - name: Interviewer
      file: Role-Interviewer.md
  

content:
  default_author: "Matt"

# Logging configuration
logging:
  level: INFO
  file: private/knowme.log 

